### ISSUE TITLE
Vue Cli 3 not working

### ISSUE THREAD

**Issue by zecampos** [championswimmer/vuex-persist#100]
I generated a project vue cli 3 from scratch and installed vuex-persist with the following settings:
![image](https://user-images.githubusercontent.com/16256291/53883895-1ac47500-3ff9-11e9-841c-0451dd2747b6.png)
---------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/16256291/53883922-2dd74500-3ff9-11e9-9bba-3328927ba27b.png)
I start the application and nothing:
![image](https://user-images.githubusercontent.com/16256291/53884056-6f67f000-3ff9-11e9-8285-e79e0ce3b477.png)
---------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/16256291/53884093-84448380-3ff9-11e9-9af7-5f2ed04b4e11.png)

What can I be doing wrong?

**Comment by championswimmer** [comment]
The states are saved only when a mutation take place.

**Comment by zecampos** [comment]
It's working, thank you!
