### ISSUE TITLE
[Feature Request] Compress / Decompress data stored

### ISSUE THREAD

**Issue by Zireael** [championswimmer/vuex-persist#102]
Hi, I wanted to propose adding an option to compress the data when putting in storage and decompress the string after retrieval. 
Using lz-string:
http://pieroxy.net/blog/pages/lz-string/index.html

Actually, I've written an example, just posting if you wanted to make use of the idea. For example, I compress the size of my stored stream down to 15% of the original so there might be use cases where it's worth the hassle.

```
import vuexPersist from "vuex-persist";
import LZString from "lz-string";

// const requestIdleCallback =
//   window.requestIdleCallback ||
//   (cb => {
//     let start = Date.now();
//     return setTimeout(() => {
//       let data = {
//         didTimeout: false,
//         timeRemaining() {
//           return Math.max(0, 50 - (Date.now() - start));
//         }
//       };
//       cb(data);
//     }, 1);
//   });

const vuexLocal = new vuexPersist({
  storage: window.localStorage, // or window.sessionStorage or localForage
  key: "vuexPersistStorage_mdvresource",
  supportCircular: true,
  saveState: (key, state, storage) => {
    // requestIdleCallback(() => { // window.requestIdleCallback not supported by IE11
      let data = JSON.stringify(state);
      if (storage && data) {
        data = LZString.compressToUTF16(data); // UTF16 version  IE11 safe
      }
      storage.setItem(key, data);
    // });
  },
  restoreState: function(key, storage) {
    let data = storage.getItem(key);
    if (data) {
      return JSON.parse(LZString.decompressFromUTF16(data)); // UTF16 version IE11 safe
    }
  }
});
```

I would appreciate help with one thing in the above - is it possible to rewrite the saveState and restoreState from the above into a promise or async/await? That's in case the compression thread lasts some time. I was able to make a bit of use of window.requestIdleCallback code seen in another post here, but I'd prefer a promise based way so that it can be polyfiled into IE11 (and could work in Node). I wasn't able to figure out way how to apply window.requestIdleCallback to the above for restoreState routine (altho, in practical terms, I wouldn't really want to wait for that one).

Also, **debounce** - would you know of a way to apply debounce (antispam) to the above saveState routine?  Let's say I'm reading data from several sources, doing a bit of manipulations on those when they hit the store and write a value or two back into store. If I'm doing compression and write/save of the store every few miliseconds, that would be inefficient. I'd be happy to add 100-200ms antispam guard when calling saveState.

Apologies, I'm still learning JS.

Thanks in advance!

**Comment by championswimmer** [comment]
Out of scope. Anyone can override the save and restore methods manually to
do this.
