### ISSUE TITLE
please show me how to use with quasar frame work

### ISSUE THREAD

**Issue by folamy** [championswimmer/vuex-persist#104]
the description in documentation doesn't work

**Comment by qmorek** [comment]
This is how I configured it with quasar v1:
`quasar new boot vuex-persist`
` app:new Generated boot: src/boot/vuex-persist.js +0ms`
` app:new Make sure to reference it in quasar.conf.js > boot +4ms`

in newly generated file _src/boot/vuex-persist.js_:
`import VuexPersistence from 'vuex-persist';`
`export default async ({ store }) => {`
`  new VuexPersistence({`
`    key: 'your-app-name',`
`  }).plugin(store);`
`};`

In _quasar.conf.js_:
`    boot: [`
`      { path: 'vuex-persist', server: false },`

Hope it helps.

**Comment by anandtripathi5** [comment]
Thank you for the solution
