### ISSUE TITLE
update Vuex types inside node_modules

### ISSUE THREAD

**Issue by khanharis87** [championswimmer/vuex-persist#11]
### Reproduction Steps
-Update to vue.js 2.5
- This might be because "Previously, we already recommend using ES-style imports (import Vue from ‘vue’) everywhere with “allowSyntheticDefaultImports”: true in tsconfig.json. The new typings will officially move to ES-style import/export syntax, so that config is no longer necessary, and users are required to use ES-style imports in all cases.
" - from https://goo.gl/pPJeiD
### Error
in 'project/node_modules/vuex-persist/node_modules/vuex/types/vue.d.ts'

```(9,40): error TS2304: Cannot find name 'Vue'.```

**Comment by championswimmer** [comment]
Is this an error in this package ? I don't think so

**Comment by khanharis87** [comment]
my bad, I do not know why there was node_modules folder in the first place in package I have! Deleted the folder and errors are gone.

**Comment by zvory** [comment]
This same thing happened to me. `node_modules/vuex-persist/nodu_modules/vue.d.ts` was ruining a bunch of things.

**Comment by maartenvanvliet** [comment]
Same thing happened for me, deleting node_modules in the package indeed does fix this. However, `node_modules` is not checked into our repository so on CI or production the error returns.

**Comment by khanharis87** [comment]
Indeed anytime I do `yarn add` any package, the `node_modules` folder is inside the package again

**Comment by nekuz0r** [comment]
I think `vuex` should be defined as a peerDependency and not a dependency to avoid this issue.

**Comment by championswimmer** [comment]
fixed
