### ISSUE TITLE
Cannot access persisted vuex store data in middleware.

### ISSUE THREAD

**Issue by simon-zhangmuye** [championswimmer/vuex-persist#111]
My vuex state has been stored in localstorage, but I cannot access vuex stored data in middleware.
I think the problem may because, when I refresh the page, middleware is loaded before vue persist sets values to vuex.
Is there any way to solve this problem?
![20190417230451](https://user-images.githubusercontent.com/10706610/56298734-447acb00-6165-11e9-84f2-f9e079f82822.png)

**Comment by Seonghui** [comment]
Did you solve the problem? I have same issue...

**Comment by pupugit** [comment]
Having the same problem too. On first page load the state gets loaded from localstorage after nuxt middleware.
