### ISSUE TITLE
Version 2.0.1 causing errors in IE11

### ISSUE THREAD

**Issue by freenetwork** [championswimmer/vuex-persist#120]
![image](https://user-images.githubusercontent.com/3347236/59240956-f4355c00-8c2f-11e9-9640-8e556155021f.png)

![image](https://user-images.githubusercontent.com/3347236/59240963-fc8d9700-8c2f-11e9-98d1-8b31a2ce3e87.png)

**Comment by freenetwork** [comment]
I fixed by
[https://cmty.app/nuxt/nuxt.js/issues/c7560](Solve)

`import VuexPersistence from 'vuex-persist/dist/umd'`

**Comment by deraw** [comment]
I think the issue should be reopened because when importing the package like this we lose typings! (But as a workaround it works)
