### ISSUE TITLE
No longer works in Internet Explorer with default config

### ISSUE THREAD

**Issue by romansp** [championswimmer/vuex-persist#138]
After upgrading to 2.1.0 app started failing with the following error:
```
Unable to get property 'toLowerCase' of undefined or null reference
```

It happens to fail where vuex-persist tries to determine `storageConstructor` value. This change was introduced quite recently in #136 (fixing #97). Code relies on the fact that `constructor.name` is always defined, however it's not the case for Internet Explorer. Described here: https://stackoverflow.com/questions/25140723/constructor-name-is-undefined-in-internet-explorer

Also `vuex-persist` is added to `transpileDependencies`.

I would like to provide a PR, though not sure how to deal with that issue. Will check for `name` not being `falsy` be enough?

IE: **11.55.17763.0**
vuex-persist: **2.1.0**

**Comment by doits** [comment]
what a coincidence, see #137 for a fix I just pushed basically in the same time!

**Comment by romansp** [comment]
@doits Oh wow, okay 👍

**Comment by doits** [comment]
Btw. I think vuex-persist should be transpiled automatically, too, so you don't need to add it to `transpileDependencies` manually. Maybe this is something that could be improved in the build process, too.

**Comment by romansp** [comment]
There is a poll for it here https://github.com/championswimmer/vuex-persist/issues/87.

**Comment by morficus** [comment]
howdy - I'm the one that introduced the fix that is causing your IE11 grief, sorry about that.
I was expecting that the TS transpiraltion process would have dealt with `constructor.name`. But I didn't realize this lib was not being transpiled down to ES5.

If you are writing stuff for IE11, are you using Babel? If so... does including the runtime pollyfill help at all?

**Comment by romansp** [comment]
@morficus 

We do use Vue CLI meaning that babel with preset-env is here, an additionally `vuex-persist` added into `transpileDependencies` config. Yet it still fails for `constructor.name` usage. I didn't spend much time looking into fixing that with providing specific runtime polyfill or adjusting browserlist config, and decided to lock on `vuex-persist@2.0.1` while #137 isn't yet merged.

**Comment by MLongz** [comment]
Will this be fixed anytime soon?

**Comment by MLongz** [comment]
> @morficus
> 
> We do use Vue CLI meaning that babel with preset-env is here, and additionally `vuex-persist` added into `transpileDependencies` config. Yet it still fails for `constructor.name` usage. I didn't spend much time looking into fixing that with providing specific runtime polyfill or adjusting browserlist config, and decided to lock on `vuex-persist@2.0.1` while #137 isn't yet merged.

So I tried to downgrade to 2.0.1 but I still get the same error, any idea?

**Comment by morficus** [comment]
@romansp @MLongz @doits  - I just opened a PR that should address this and a few other issues opened against this project.
please take a look and let me know what you think.
