### ISSUE TITLE
falling back to serialisation when minified

### ISSUE THREAD

**Issue by mech01nc01** [championswimmer/vuex-persist#144]
related to: [localForage object stored as string](https://github.com/championswimmer/vuex-persist/commit/7575ebffb1e4a42552bdf89e64e3257b32ccfe3e)

in src/index.ts you changed from storageConfig.name to storage.constructor.name (2.0.1 -> 2.1.0)
this works well in development, but  when localforage gets minimized, storage.constructor.name will become something like "a" oder "e" or whatever, and then it breaks ;(

**Comment by mech01nc01** [comment]
as a Workaround in locally edited esm/index.js and added the old check in Addition:

`((storage && storage.constructor && storage.constructor.name.toLowerCase()) === 'localforage') || ((storage && storage._config && storage._config.name.toLowerCase()) === 'localforage')`

but would be nice if it would work out of the box ;)

**Comment by tafkanator** [comment]
as another workaround it is possible to overwrite `saveState` method so that it wont even try to check for localForage
```javascript
new VuexPersist({
	// ...
	asyncStorage: true,
	saveState: (key, state, storage) => {
		if (storage) {
			storage.setItem(key, state)
		}
	},
})

```

**Comment by mech01nc01** [comment]
yeah that would be better then manipulating the source … thanks for the tip!

**Comment by morficus** [comment]
@tafkanator and @mech01nc01 - I just opened a PR that should address this.
please let me know what you think.
