### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by Tronix117** [championswimmer/vuex-persist#149]
Hello,

When using vue.JS in an environment that does not provide `window` (like in a mobile environment) and thus does not provide `window.localStorage`, this plugin does not work when used with `production` environment.

Code in default is there : https://github.com/championswimmer/vuex-persist/blob/50118061486d11572fbe88a6d4acf86b4b9e0ce8/src/index.ts#L61
You should not assume window will always be defined.

Quick'n'dirty fix is to do `storage: new MockStorage()` when initializing the module.

**Comment by goatandsheep** [comment]
I think what I did wrong here is that `window.localStorage` _needs_ to be tested with a try-catch
![image](https://user-images.githubusercontent.com/5570628/89473446-db033f00-d750-11ea-91f3-30dd390e80f7.png)
