### ISSUE TITLE
Nuxt page refresh restores state but you can only access it via computed properties. 

### ISSUE THREAD

**Issue by msacchetti** [championswimmer/vuex-persist#153]
This plug-in works great but you can't access the restored state in any of the Vue / Nuxt lifecycle hooks or the data object. Using a fresh install of Nuxt in SPA mode.

The restored state works perfectly only in computed properties using "this.$store.state". if you try to access "this.$store.state"  in data(), created(), mounted(), asyncData(), or fetch(), it returns your default blank state object or undefined.

A fix for this is removing the "window.onNuxtReady" wrapper function. It then allows you to access the restored state in those lifecycle methods.

Does anyone know why this happens? And if it's production safe to init the plugin without the "window.onNuxtReady" wrapper function? 

Edit: In my case, i needed to set a data property from the store so i figured out another solution, setting a watcher to watch the computed property and then set the data - but now it only works ON reload and not on page navigation :) 

```
data(){
     return { industry: [] }
    },
    watch: {
      mycomputedProperty(value) {
        this.industry = value
      }
  }
```

**Comment by mithom** [comment]
do you by any chance use async storage? then you can just await the store.restored promise for it to be available, not sure when the sync storage happens, but i would assume it would be available in most hooks. for the hooks that you are using: please check for which hooks the store is already initialised, because it is impossible to hydrate a store that hasn't been initialised yet.

**Comment by msacchetti** [comment]
I don't use async storage.
The store is usually available in mounted and data, I use that all the time. I assume onNuxtReady fires after all the hooks so that was causing the issue.i can't find much documentation on onNuxtReady unfortunately.
I'll try out using the store.restored promise as a solution and report back.

Thanks

**Comment by saint777** [comment]
same problem, the is state is empty

**Comment by msacchetti** [comment]
> same problem, the is state is empty

I have not figured out a solution yet. i am going to try the other 2 vue-persistedstate plugins and see if i have any luck

**Comment by mithom** [comment]
Reading your issue again and having some more vue knowledge, it is pretty clear why it happens. OnNuxtReady happens after your complete page has loaded for the first time, it is like onDocumentReady but with the framework js already run. This means that your components actually have to be created before your onnuxtready and that all the lifecycle hooks you mentioned have already run (as it are all run once hooks).
Removing the OnNuxtReady will make your code execute more early.
I do not think this should be changed, as more as you should work around it in some way maybe

**Comment by msacchetti** [comment]
Thanks for your help. Does store.restored work with sync storage or only with async?

 I am going to try to init the plug-in within the store/index.js file itself. I fooled around with that today and it seemed to work so far. I'll report back

**Comment by mithom** [comment]
@msacchetti i just checked my code and it seems i don't use the nuxt plugin but do exactly as you said, i just create a vuex-persist instance and add it as a vuex store plugin. I muat've read over that part of the docs hehe, but i haven't found any issues with this approach.

(I think the nuxt plugin didn't exiat yet when i first started using this)

**Comment by msacchetti** [comment]
Well i'll be darned. I just tried it again with a fresh install of Nuxt and the issue is no longer there. My original post i was using "nuxt": "2.0.0"

With "nuxt": "2.10.2", i followed the same setup as i did before (following the readme "Tips for NUXT") like so:

```
// ~/plugins/vuex-persist.js
import VuexPersistence from 'vuex-persist'

export default ({ store }) => {
  window.onNuxtReady(() => {
    new VuexPersistence({
    /* your options */
    }).plugin(store);
  });
}
```

Now on page refresh i can access the store in any of the lifecycle methods. Both of the examples below work, even with the wrapper function window.onNuxtReady

```
data() {
  return {
   // this.prevState is successfully set to the persisted state
    prevState: this.$store.state
  }
},
mounted() {
  // console logs the persisted state successfully
  console.log(this.$store.state)
}
```

I guess we will never know what was happening before, but whatever they changed in Nuxt since 2.0.0 fixed the issue.

**Comment by mithom** [comment]
There has been a change in await nuxt.ready in 2.8 i think, maybe that caused it, not sure if onNuxtReady uses the same principle. It will remain a mystery for life to come. What did we learn: update dependencies :-)

**Comment by msacchetti** [comment]
a correction for anyone with the issue: 

i was using _nuxt 2.2.0_, not 2.0.0

**Comment by lopermo** [comment]
Having the same problems. Nuxt most likely changed something?
Has anyone found any solution to this? I can only seem to restore the store after mounted.

**Comment by mithom** [comment]
please read other comments that say it is solved, update your nuxt version or follow any of the workarounds

**Comment by lopermo** [comment]
> please read other comments that say it is solved, update your Nuxt version or follow any of the workarounds

I'm using the last version of Nuxt, and I cannot find any workaround. Do you mind sending one of those workarounds here?
