### ISSUE TITLE
vue-cli with Element UI  integration vuex-persist

### ISSUE THREAD

**Issue by shadow198** [championswimmer/vuex-persist#16]
it's can save to localstorage,but has error at console: 
[Vue warn]: Error in callback for watcher "function () { return this._data.$$state }": "Error: [vuex] Do not mutate vuex store state outside mutation handlers."

**Comment by championswimmer** [comment]
You can use the strict mode to prevent that warning (check https://github.com/championswimmer/vuex-persist#support-strict-mode )
