### ISSUE TITLE
Support for writing to storage in web extensions

### ISSUE THREAD

**Issue by RizziFrank** [championswimmer/vuex-persist#170]
Would be nice if support for chrome.storage.local was built in. I created a go-between object for now, but maybe it can be integrated. Same for chrome.storage.sync Also requires asyncStorage to be true.

	const chromeLocalStorage = {
	    setItem: (key, value) => {
	        return new Promise((resolve, reject) => {
	            var newItemCache = {} // note: storage.local needs an object with a property of the key name, so newItemCache is not what we're saving, value is.
	            newItemCache[key] = value
	            chrome.storage.local.set(newItemCache, () => {
	                chrome.runtime.lastError
	                    ? reject(Error(chrome.runtime.lastError.message))
	                    : resolve()
	            })
	        })
	    },
	    getItem: (key) => {
	        return new Promise((resolve, reject) => {
	            chrome.storage.local.get(key, (obj) => {
	                chrome.runtime.lastError
	                    ? reject(Error(chrome.runtime.lastError.message))
	                    : resolve(obj[key]) // storage return is always boxed
	            })
	        })
	
	    },
	    removeItem: (key) => {
	        return new Promise((resolve, reject) => {
	            chrome.storage.local.remove(key)
	        })
	    },
	    clear: () => {
	        return new Promise((resolve, reject) => {
	            chrome.storage.clear(() => {
	                chrome.runtime.lastError
	                    ? reject(Error(chrome.runtime.lastError.message))
	                    : resolve()
	            })
	        })
	    }
	}
	const vuexLocal = new VuexPersistence({
	    storage: chromeLocalStorage,
	    asyncStorage: true
	})

**Comment by championswimmer** [comment]
use asyncStorage = true and set chrome.storage.local as storage ?

**Comment by championswimmer** [comment]
But as a library I do not intend to support non DOM-standard storages. You can always shim it the way you've done. :)

**Comment by doutatsu** [comment]
@RizziFrank Have you managed to get it working with modules? Having a bit of trouble getting them to work with your code

**Comment by doutatsu** [comment]
Nvm, it works great. Due to the async nature, I had to wait for the state to get restored first
