### ISSUE TITLE
Remove lodash as dependency

### ISSUE THREAD

**Issue by simplenotezy** [championswimmer/vuex-persist#172]
Could we perhaps consider removing the dependency on lodash, since we only use one method, and it takes up 75% of the whole package size?

![image](https://user-images.githubusercontent.com/3786627/74587014-d9e92480-4fed-11ea-8910-8fb4b78a0b53.png)

In es6 it's done farily easy:

	const objectOne = {
		lat: -51.3303,
		lng: 0.39440
	}

	const objectTwo = {
		id: 'qwenhee-9763ae-lenfya',
		address: '14-22 Elder St, London, E1 6BT, UK'
	}

	const newItem = Object.assign({}, objectOne, objectTwo);

	console.log(newItem);

**Comment by JordyLangen** [comment]
The problem with using `Object.assign({}, objectOne, objectTwo);` is that it does not create a deep clone (?)

**Comment by BenjjinF** [comment]
I'm guessing that `import lodashMerge from 'lodash.merge'` isn't being tree shaken.

May shifting to import `{ merge as lodashMerge } from 'lodash'` or something would do the trick.

**Comment by championswimmer** [comment]
> I'm guessing that `import lodashMerge from 'lodash.merge'` isn't being tree shaken.
> 
> May shifting to import `{ merge as lodashMerge } from 'lodash'` or something would do the trick.

Will try this
