### ISSUE TITLE
DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'vuex' exceeded the quota.

### ISSUE THREAD

**Issue by nassmim10** [championswimmer/vuex-persist#186]
Hi,

Today, I started having this error message:

"DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'vuex' exceeded the quota."

Below the app configuration I have:

const vuexLocalStorage = new VuexPersist({
  key: 'vuex', 
  storage: window.localStorage, 
  reducer: state => ({
  	user: state.user,
  	userConnected: state.userConnected
  }),
})

const store = new Vuex.Store({
	state,
	mutations,
	plugins: [vuexLocalStorage.plugin, createPersistedState(), createMutationsSharer({predicate: ['mutation1', 'mutation2']})],
	modules: {
		user,
		...
	},
});

I have tried to find a solution for hours but still no clue how to sort this out.

So far, I have tried on different web browsers firefox, chrome and safari; I have cleared the cache but still same error. 
Also tried to remove the vuexLocalStorage from the store plugins, but it did not change anything.

Would someone have a solution to fix, tutorial to follow to change the cache strategy or any other way?
I am working on:
- mac OS Mojave
- vuejs 2.5.9
- vue-axios 2.0.2
- vuex-persistedstate 2.5.4

**Comment by Jewcub** [comment]
same issue here

**Comment by nassmim10** [comment]
Anyone to help ? Please let me know if my issue needs to me more detailed

**Comment by nassmim10** [comment]
Up please !

**Comment by carlosmart7104** [comment]
Same issue :C

**Comment by nassmim10** [comment]
For those who're stuck in this, actually my problem was coming from the fact I was storing too much data. And the module involved was actually vuex-persistedstate not vuex-persist. I introduced a reducer in the vuex-persistedstate object and cached fewer data. Now it works again. But I couldn't figure out why it used to work and started having issues so suddenly...

**Comment by Jewcub** [comment]
I switched to localforage from localforage and that fixed it as well



---Original---

**Comment by TitanFighter** [comment]
@Jewcub 
> localforage

from
> localforage

? :)

**Comment by Jewcub** [comment]
Oops. From localstorage to localforage! Fixed it.



---Original---
