### ISSUE TITLE
filter function is never called for sync storage

### ISSUE THREAD

**Issue by dubrowsky** [championswimmer/vuex-persist#20]
Hi! Looks like the `filter` function [is called](https://github.com/championswimmer/vuex-persist/blob/master/src/index.ts#L146) only inside the `if (this.asyncStorage) {` branch, otherwise `saveState` is called [without any filtration](https://github.com/championswimmer/vuex-persist/blob/master/src/index.ts#L204). Is it ok?

**Comment by championswimmer** [comment]
thanks for reporting. fixed it in v1.1.0
