### ISSUE TITLE
Support for Vuex 4 and Vue 3?

### ISSUE THREAD

**Issue by ux-engineer** [championswimmer/vuex-persist#200]
Sorry if this is a non-issue, as I haven't upgraded my Vuex codebase (that is using this plugin) yet to Vuex 4...

But I was wondering do you need to build support for Vuex 4 with Vue 3, and how is that upgrade process going on now that Vue 3 reached its first stable release (with Vuex 4 still in beta)?

**Comment by championswimmer** [comment]
It is already supported
