### ISSUE TITLE
Vuex version confusion

### ISSUE THREAD

**Issue by Raphx** [championswimmer/vuex-persist#21]
Hello!

The README stated that Vuex > 2.1 is supported. On the other hand, package.json specifies `"vuex": "^3.0.1"`.

Which version of Vuex is actually supported?

**Comment by championswimmer** [comment]
The vue used depends on *your* package.json

Mine is used to only run tests :)

**Comment by Raphx** [comment]
Ah yes, I forgot to mention that it is the one on `peerDependencies` :p 

Since vuex-persist will be installed along side with vuex, the peer dependency should be something like `>=2.1` ?

I'm using vuex v2.3.1, and whenever I install the package, I always get:

`warning " > vuex-persist@<some_version>" has incorrect peer dependency "vuex@^3.0.1".`

**Comment by championswimmer** [comment]
ah okay ! got it 

will fix

**Comment by pSchaub** [comment]
@championswimmer Any updates? I also see this bug in my project.
```
warning "ocp-frontend-spieler > vuex-persist@1.1.3" has unmet peer dependency "vuex@> 2.5".
```
I also use Vuex 3.x
