### ISSUE TITLE
Save state conditionally

### ISSUE THREAD

**Issue by danielsvane** [championswimmer/vuex-persist#22]
Thanks for this great plugin!

I am using the plugin to save the users login token, and some private data. I want to use a checkbox in the login form, to choose whether the store should be saved to localstorage. Do you have any ideas how to do this, using this plugin?

**Comment by benitogf** [comment]
hi, you can use the filter [param](https://github.com/championswimmer/vuex-persist#constructor-parameters--)

**Comment by championswimmer** [comment]
You can add any condition you want in `filter` param

It is a function that returns a boolean. Add whatever logic you want inside it :)

**Comment by danielsvane** [comment]
Alright thanks, will try it out
