### ISSUE TITLE
using vuex-persist in axios interceptors will throw error

### ISSUE THREAD

**Issue by stupidsongshu** [championswimmer/vuex-persist#23]
![1](https://user-images.githubusercontent.com/20420409/35024740-3431db12-fb7c-11e7-8390-168193d9eb6e.png)
I want to set loading status in the axios's interceptor when emit a http request, but I find the js doesn't work after the http error(eg.timeout or the net is terrible) is catched.

**Comment by championswimmer** [comment]
Can you provide the stacktraces and console error statements ?
