### ISSUE TITLE
Causes issues with the beta Vue DevTools

### ISSUE THREAD

**Issue by rowanwins** [championswimmer/vuex-persist#233]
Hiya,

Just a note that I experienced using the beta Vue DevTools when using this plugin. The DevTools appear to get stuck just showing the initial values.

See some comments over in https://github.com/vuejs/devtools/issues/1456

Cheers

**Comment by jaitaiwan** [comment]
I've taken a look at the plugin code and it's not really Vue 3 compatible. The only mode that I believed would work with Vue 3 is strictMode and it fails to work because Vue3 doesn't include _vm.$set anymore. The library needs to be updated to work.

**Comment by andreibaca** [comment]
I can confirm that The DevTools appear to get stuck just showing the initial values in Vue3 with Vuex4.
@jaitaiwan Is there an alternative to vuex persist that works with Vue3 and async storage?

**Comment by jaitaiwan** [comment]
Sorry it's been so long @andreibaca. There isn't an alternative but I'm considering forking off this repo and fixing it. vuex-persistedstate which I've been using doesn't have anything remotely close to something that works with vuex 4
