### ISSUE TITLE
Unhandled Promise Rejection: QuotaExceededError: The quota has been exceeded.

### ISSUE THREAD

**Issue by hcancelik** [championswimmer/vuex-persist#267]
Getting `Unhandled Promise Rejection: QuotaExceededError: The quota has been exceeded.` error when setting a simple key/value (string).

It seems that this only happens on Safari (and/or Safari/Chrome in iPhone).

Any idea how I can prevent the JS error?

It happens on `this.saveState(this.key, this.reducer(state), this.storage);` line
```
     /**
             * Sync version of plugin
             * @param {Store<S>} store
             */
            this.plugin = (store) => {
                const savedState = this.restoreState(this.key, this.storage);
                if (this.strictMode) {
                    store.commit('RESTORE_MUTATION', savedState);
                }
                else {
                    store.replaceState(merge(store.state, savedState || {}, this.mergeOption));
                }
                this.subscriber(store)((mutation, state) => {
                    if (this.filter(mutation)) {
                        this.saveState(this.key, this.reducer(state), this.storage);
                    }
                });
                this.subscribed = true;
            };
        }
```

**Comment by andrewfenn** [comment]
You've run out of localstorage space in the browser. i.e. gone over 5 - 10 MB of data being stored in your browser's localstorage.

**Comment by hcancelik** [comment]
@andrewfenn ~looks like the data I have is less than 3MB.~

You were right. It was slightly over 5MB in total. 

I still think the package shouldn't throw an error so I created a work to try catch the issue. 

Thanks for the response.
