### ISSUE TITLE
localForage support

### ISSUE THREAD

**Issue by invernizzi** [championswimmer/vuex-persist#3]
Hi Arnav,
first of all, thank you for releasing vuex-persist.
You mention on your readme that localforage is supported.
However, `new VuexPersistance(storage: localforage})` doesn't work - it surfaces an error related to localforage being asynchronous (VuexPersistance is trying to JSON decode a JS promise).
Any tip how to make this work?

**Comment by championswimmer** [comment]
Ah, will have to make some changes for that. Let me add this to my todo.

**Comment by sandrooco** [comment]
Same problem here.
@championswimmer Do you think you can implement support for this shortly? This package is great and really does everything a indexeddb vuex plugin should do. Although I have very limited experience with offline stuff, let me know if I can help with anything.

**Comment by agonzalezml** [comment]
I'm also interested in this! It seems the best way of enhancing this awesome package.

**Comment by championswimmer** [comment]
So I will make restoreState and saveState async functions (change their signatures to `(): Promise` )
I have a Vue project to work on this weekend, and it will require some `vuex-persist` help, I'll improve upon 2-3 things, including this localForage support then.

**Comment by Tronix117** [comment]
Any news about that ?

**Comment by RichiCoder1** [comment]
If yah don't get around to it, will probably tackle this too @championswimmer :)

**Comment by gijo-varghese** [comment]
@championswimmer can I expect it soon?

**Comment by wopian** [comment]
`0.1.4` / https://github.com/championswimmer/vuex-persist/commit/2170a51cc2513d440d5f7c902af2eb0df8704b4e adds support for IndexedDB/localforage

**Comment by championswimmer** [comment]
@gijo-varghese use v0.5.0

You simple need to use 
```js
new VuexPersistence({
    storage: localforage
})
```

**Comment by to-svarghese** [comment]
Is localForage is ready to work with vuex-persist? 

I tried to use localforage for storing dala loacally and to work offline. When I use localforage with vuex-persist data is storing and when I refresh the page all data stored is lost and is reset to initial values. What could be the reason? But it is working when I change that to localstorage.

**Comment by TimonPost** [comment]
I am experiencing the same, have you found the reason?

**Comment by ulf1** [comment]
@TimonPost @to-svarghese 
I had the same symptom rn. 
this helped: https://github.com/championswimmer/vuex-persist/issues/117#issuecomment-493906644

example:

```
import VuexPersist from 'vuex-persist';
import localForage from 'localforage'
const vuexStorage = new VuexPersist({
  ...
  storage: localForage,
  asyncStorage: true, // <<< ADD THIS
  ...
});
```

**Comment by yeus** [comment]
> ```
>   asyncStorage: true, // <<< ADD THIS
> ```

this worked!, thx @ulf1
