### ISSUE TITLE
tsconfig.json causing error in VS Code

### ISSUE THREAD

**Issue by chewy94** [championswimmer/vuex-persist#36]
VS Code is yelling at me after adding the package:
`No inputs were found in config file '/Users/sean/Desktop/Development/Vuetify/dapp-masternode-vue/node_modules/vuex-persist/tsconfig.json'. Specified 'include' paths were '["src"]' and 'exclude' paths were '["node_modules","test/**/*"]'.`

Everything appears to be working properly, it just turns some of VS Code's UI red since it is being recognized as a problem.

**Comment by championswimmer** [comment]
Oh yeah okay, I guess I should not put the tsconfig.json into my dist
tarball.

**Comment by chewy94** [comment]
Thanks 😄

**Comment by chewy94** [comment]
Fixed with recent release

**Comment by LetovGr** [comment]
Its going again in my VS Code, i use last version of this plugin
