### ISSUE TITLE
Can this be a dev dependency?

### ISSUE THREAD

**Issue by chewy94** [championswimmer/vuex-persist#37]
Just a question... Does this have to be added as a production dependency or can it be like Vuex and be a dev dependency?

**Comment by championswimmer** [comment]
Not sure if you understand the build process properly. After build, everything is compressed into vendor.js so *everything* is in your /dist folder that you need to run the *frontend* of your website. 

In that sense, yes, this can also be devDependency

None of the node_modules *run* in production. In production the vendor.js runs inside user's browser :)
