### ISSUE TITLE
How to clear the localStorage, not working after using localStorage.clear() on a mutation

### ISSUE THREAD

**Issue by ghost** [championswimmer/vuex-persist#4]
I have this code to clear the localStorage, it work but only sets to false the `state.user.connected` and `state.user.role` to an empty string. I need to remove all inside localStorage.

    SIGN_OUT(state) {
            firebase.auth().signOut()
            localStorage.clear()
            state.user.connected = false
            state.user.role = ''
            router.push('/')
    }
![example](https://user-images.githubusercontent.com/31114164/31363622-9caa9712-ad2d-11e7-8756-4b473c780cb4.jpg)

**Comment by championswimmer** [comment]
use `window.localStorage.clear()`

**Comment by enghelewa** [comment]
It will never be cleared. Because you are clearing then writing back to the storage.
you will find a better way of clearing the storage here #52
