### ISSUE TITLE
how do i set expire time to hours or minutes

### ISSUE THREAD

**Issue by dumebi** [championswimmer/vuex-persist#42]
`const vuexCookie = new VuexPersist({
  restoreState: (key, storage) => Cookies.getJSON(key),
  saveState: (key, state, storage) => Cookies.set(key, state, {
    expires: 3
  }),
  modules: ['user'] // only save user module
})`
I do not know what the 3 means. How do i set it to minutes

**Comment by championswimmer** [comment]
It is days.

**Comment by championswimmer** [comment]
cookies are saved in days only as per JS-Cookie library.
