### ISSUE TITLE
Cannot store cyclic object

### ISSUE THREAD

**Issue by rossng** [championswimmer/vuex-persist#44]
I am trying to store a [web3.js](https://github.com/ethereum/web3.js) `contract` object with vuex-persist, but I get the following error:

```
TypeError: cyclic object value
```

It looks like there are [ways](https://github.com/douglascrockford/JSON-js/blob/master/cycle.js) to remove/restore cycles from JSON objects. This feels like something that vuex-persist should do automatically.

**Comment by championswimmer** [comment]
Could you add a test with a cyclic object (that will fail as of now), so I can fix it and make it pass.

**Comment by rossng** [comment]
Submitted PR #45

**Comment by rossng** [comment]
Oops, wrong button!

**Comment by championswimmer** [comment]
fixed in v1.2

**Comment by ryleyb** [comment]
I think the documentation for this is wrong - vuex-persist module should include `circular-json` in your package.json.  In v1.2 I get this error if I don't install it myself (despite not enabling it in my vuex-persist config):

```
ERROR in ./node_modules/vuex-persist/dist/index.js
Module not found: Error: Can't resolve 'circular-json' in '{redacted}/node_modules/vuex-persist/dist'
 @ ./node_modules/vuex-persist/dist/index.js 7:19-43
...
```

**Comment by rulrok** [comment]
Just pointing out, I had the same problem as @ryleyb . I had to install `circular-json` package by myself.

**Comment by championswimmer** [comment]
@rulrok yes it is not included by default 

as the doc states, you have to install it 
https://github.com/championswimmer/vuex-persist#circular-states

would be unfair to add to someone's node_modules, unless the are using circular objects

**Comment by ryleyb** [comment]
Hi, unfortunately I think you're missing the point. It's not optional - your module crashes if **I** don't install `circular-json` the second I install `vuex-persist`.   Doesn't matter if I disable circular-json via the `supportCircular` option.

**Comment by championswimmer** [comment]
@rulrok even with v1.4.0 ?

**Comment by ryleyb** [comment]
I just upgraded to 1.4.0 and it fails on the `require('circular-json')` in your code.  This, despite me having `supportCircular:false` in my options for vuex-persist.  So, I suspect somewhere in the compilation process all `require` calls are being hoisted.  My build uses webpack and babel.  I wonder if @rulrok has something similar, and @championswimmer does not?

**Comment by rulrok** [comment]
@championswimmer I'm have version `"vuex-persist": "^1.4.0"` on my `package.json` file.
