### ISSUE TITLE
Allow transform models when restore state

### ISSUE THREAD

**Issue by Koc** [championswimmer/vuex-persist#46]
Hello!

I am using typescript (not sure does it matter). I'm trying create model classes for stored data. For example create class `CartItem` with some methods, like `getSimpleProductId`. And next problem occurs: when plugin restores state we raw object instead of class. Is it possible create something like `reducer` callback option, but for restoring? In this callback we can create class objects instead of plain objects.

**Comment by championswimmer** [comment]
You should override restoreState and saveState yourself for that then

**Comment by championswimmer** [comment]
Similar to https://github.com/championswimmer/vuex-persist/issues/47
Same solution

**Comment by Koc** [comment]
Heh, interesting, that next issue is similar to my. But after getting some more expirience with Vuex I have understood that my original question was wrong. Better sollution - use getters from Vuex.

```typescript
const getters = {
    [Getters.cartId]: (state: CartState): string | null => state.cartId,
    // create models from state (persisted or not - does not matter)
    [Getters.cartItems]: (state: CartState): Array<CartItem> => state.cartItems.map(cartItemRaw => CartItem.fromRawData(cartItemRaw)),
    [Getters.cartItemsSubtotal]: (state: CartState): number => state.cartItems.reduce((total: number, cartItem: CartItem) => total + cartItem.price * cartItem.qty, 0),
};
```

@championswimmer WDYT about this approach? Am I right or am I again moving in wrong direction?
