### ISSUE TITLE
Object functions not persisted

### ISSUE THREAD

**Issue by chewy94** [championswimmer/vuex-persist#47]
Hello!

I am currently trying to commit an object to my vuex state that contains functions as some of its attributes.
For example if I commit this to state using a mutation:
```js
{
  attr1: [],
  attr2: '',
  attr3: function()
}
```

After the mutation my state looks correct:
```js
{
  attr1: [],
  attr2: '',
  attr3: function()
}
```

But when I refresh the page or check localStorage, `attr3` is simply dropped from the object and now looks like this:
```js
{
  attr1: [],
  attr2: ''
}
```

Any thoughts on the subject? If you need more info just let me know.

**Comment by championswimmer** [comment]
This plugin persists 'data' not 'objects'. Not an intended feature of this plugin.

**Comment by chewy94** [comment]
If objects are not in the scope of the project that is fine, but I am a little confused because I am committing the object to my vuex store as data. Do you mean `data` is simple structures as in just a string or just a number? I would think that persisting anything that a user commits to their vuex store is within the scope of this project

**Comment by chewy94** [comment]
Gotcha :) Thanks for being so active and maintaining this amazing project

**Comment by championswimmer** [comment]
To explain a little better (sorry I shot that off as a mail from my mobile earlier): 

It won't be technically possible to reconstruct objects at the library layer, unless the library can infer the classes. Which would either mean as much manual effort as writing your own `restoreState` or a bloated library code

**Comment by chewy94** [comment]
I actually forgot that `restoreState` was something I could override and is a great option for me. Luckily in my case I have the info needed to reconstruct the object at runtime even without `restoreState`. But, I will go with `restoreState` and call that the solution. Thanks for giving more details
