### ISSUE TITLE
Object.assign function not found in older browser

### ISSUE THREAD

**Issue by superpikar** [championswimmer/vuex-persist#5]
Hello, I use vuex-persist to build a mobile-web app as an android webview. 
When I open my mobile-web app using Galaxy S3 (Android version 4.4.4), I got this error 
```
Uncaught TypeError: Object function Object() { [native code] } has no method 'assign
```

The error occurs because the browser doesn't support object.assign. This problem solved by adding object-assign package 
```
// in dist/index.js
Object.assign = require('object-assign');
```

**Comment by championswimmer** [comment]
Let me compile to a lower js target. It should work

**Comment by championswimmer** [comment]
On second thoughts, I am not making any changes here. If you want to support older browsers, simply depend on `object-assign` and  use `Object.assign = require('object-assign');` in your entry js file
