### ISSUE TITLE
store.registerModule overwrites persisted state

### ISSUE THREAD

**Issue by robbeman** [championswimmer/vuex-persist#50]
Consider this example code:

```
const store = new Vuex.Store({
  plugins: [createPersistedState(persistedStateOptions)]
});

import user from './user.js';
store.registerModule('user', user);
```

This will load the persisted state from localStorage (or other) and then it will be overwritten by the state defined in the "user" module. I think I understand why this is happening, but a small warning about this in the documentation could come in handy for some people.

This on the other hand will work fine:
```
import user from './user.js';

const store = new Vuex.Store({
  modules: {
    user
  },
  plugins: [createPersistedState(persistedStateOptions)]
});
```

I can use the latter in my project, but I started out with the first implementation and spent some time finding out what prevented the persisted state from being restored.

**Comment by robbeman** [comment]
PS: I don't think this should be – or can be? – fixed, but just stated in the documentation to prevent confusion.

**Comment by championswimmer** [comment]
True! If you can add a paragraph about this to README, would love to accept
a PR :)

**Comment by robbeman** [comment]
Done, I added this in the "examples" section. Not sure if that is the best place, but it's there and that's what counts 👍

**Comment by japboy** [comment]
just wondering if there are any possibility to support to restore state from dynamic module registration...? my vuex structure heavily depends on dynamic module and it would be great if restoring the state is possible :D

**Comment by webcoderkz** [comment]
@japboy, @championswimmer i just wonder about the same.

**Comment by mudlee** [comment]
me too...

**Comment by salam0smy** [comment]
This is how I got mine to work with dynamic modules:
```
if (!DiscoveryStoreModule.registered) {
        store.registerModule('discovery', DiscoveryStoreModule, {
          preserveState: !!store.state['discovery'],
        });
        DiscoveryStoreModule.registered = true;
}
```
Two things to note here:
When the state is restored you will need to pass `preserveState: true` so that you don't override the persisted state.
And to avoid registering the module twice you can add a customProp to the module object 
`DiscoveryStoreModule.registered`

**Comment by seyfer** [comment]
@championswimmer any comment on solution proposed above by @salam0smy please? Is it valid?

**Comment by thefoxie** [comment]
@seyfer yeah it works. I just configured it with https://github.com/ElMassimo/vuex-stores. 
```js
registerAndGetStore(VuexStore, storeModule, { preserveState: true });
```

**Comment by fezzzza** [comment]
> This is how I got it to work with dynamic modules:
> 
> ```
> if (!DiscoveryStoreModule.registered) {
>         store.registerModule('discovery', DiscoveryStoreModule, {
>           preserveState: !!store.state['discovery'],
>         });
>         DiscoveryStoreModule.registered = true;
> }
> ```
> 
> Two things to note here:
> When the state is restored you will need to pass `preserveState: true` so that you don't override the persisted state.
> And to avoid registering the module twice you can add a customProp to the module object
> `DiscoveryStoreModule.registered`

This also appears to be a more appropriate approach for TypeScript implementations:
@Module({
  namespaced: true,
  name: "users",
  store,
  dynamic: true,
  preserveState: !!store.state["users"],
})

...although I would like to figure out how to avoid registering the module twice in this case too.
