### ISSUE TITLE
How to clear storage?

### ISSUE THREAD

**Issue by panndoraBoo** [championswimmer/vuex-persist#52]
I'm sorry if this is already described somewhere, I can't seem to find it. When my user logs out of the application I want the storage to be cleared. 
I use 
  window.localStorage.clear();
But when I look in local storage or if I log window.localStorage, I still see my data and it's not cleared.

**Comment by enghelewa** [comment]
You need to wait for the promise of logout dispatch like described below. 
```
this.$store.dispatch('logout').then(() => {
   window.localStorage.clear();
   this.$router.push('/login');
});
```
If your store's logout routine contains clear functionalities, for example setting the state variable to empty string and after that you cleared the storage. then you will be in a situation of clearing and writing at the same time.

Another solution you may go with is to set `window.localStorage.clear();` inside a timeout say for 100ms

**Comment by tvdeyen** [comment]
You probably want to only remove the Vuex store from localStorage instead of clearing the whole local store that might hold data from other sites?

```js
window.localStorage.removeItem('vuex'); // or whatever you set to `key` while instantiation
```

**Comment by tvdeyen** [comment]
And most likely this plugin wants to provide a way to clear it's own store from whatever storage solution you are using.

**Comment by stalniy** [comment]
This plugin have a separate option, like `clearOn: <mutationName>`. So, I can do something like `clearOn: 'logout'` and later when `store.commit('logout')` it clears everything by itself

**Comment by championswimmer** [comment]
@stalniy that sounds like a good suggestion, will try to implement that!

**Comment by heihachi88** [comment]
> This plugin have a separate option, like `clearOn: <mutationName>`. So, I can do something like `clearOn: 'logout'` and later when `store.commit('logout')` it clears everything by itself

I couldn't find info about this option, could you provide a link in documentation?

**Comment by yooouuri** [comment]
There is no option `clearOn` @stalniy

**Comment by stalniy** [comment]
It was a suggestion to implement something like that

**Comment by sneko** [comment]
Hi,

Any advice of the best practice to at the same time remove the persisted state and also reset the runtime state? (since the user logs out, I don't want the next user on the same device having the previous module states).

Should I implement a `reset` mutation on all my namespaced modules and loop over modules to trigger them? Or implement a global method that directly modify the global store state?

Thank you,

**Comment by BartusZak** [comment]
Solution provided by @tvdeyen doesn't work for me.

**Comment by TitanFighter** [comment]
```
// state.js
export const initialStateGlobalSettings = () => ({
  browserWindowWidth: 0,
  browserWindowHeight: 0,

  isMobileDevice: false,
  routeNamePrev: 'Home'
})

export default initialStateGlobalSettings()
```

```
// mutations.js
import { initialStateGlobalSettings } from './state'

export default {
  resetStateGlobalSettings (state) {
    const initial = initialStateGlobalSettings()
    Object.keys(initial).forEach(key => { state[key] = initial[key] })
  },

  // ...
  // Other mutations
}
```

Call `resetStateGlobalSettings` when you need to reset state.
