### ISSUE TITLE
Add .idea folder to .gitignore, .npmignore and remove it from repo

### ISSUE THREAD

**Issue by xodock** [championswimmer/vuex-persist#54]
All in a title. That folder shouldn't be in git. We don't need your jetbrains settings, even if want to contribute.

Thanks for great plugin!

**Comment by championswimmer** [comment]
It is not there in repo. Where did you find it ?

**Comment by xodock** [comment]
@championswimmer sorry, man, it's not in repo, but:
![image](https://user-images.githubusercontent.com/29227182/41512613-9126fa16-7294-11e8-8c36-61ac56c95133.png)
