### ISSUE TITLE
filter is still saving the mutation to localforge

### ISSUE THREAD

**Issue by cj** [championswimmer/vuex-persist#55]
Currently I have:

```javascript
const ignoreMutations = [
  'currentUser/setAuthenticated',
  'currentUser/setLoggedIn',
  'resource/setTypes',
  'resource/setCurrentVideo',
]

const vuexPersist = new VuexPersist({
  asyncStorage: true,
  key: 'vuex',
  storage: localForage,
  filter: mutation => !ignoreMutations.includes(mutation.type),
}).plugin
```

When I check localforge the data has been saved, shouldn't this not be the case?

![](https://image.prntscr.com/image/oRbzDxHLQeaY3ymaH5ZN6g.png)

**Comment by morphatic** [comment]
You see that  :warning: `Data may be stale` right there near the top? Try clicking the :arrows_clockwise: button and see if the mutations you wanted to ignore are still there. You might also try completely clearing the storage (see the "Clear Storage" link on the left) and then re-run your app to make sure your ignored mutations are actually being ignored.

**Comment by cj** [comment]
@morphatic thank you for the response.  I had already tried all the things you mentioned before posting, including deleting the storage to make sure.  Here's a screenshot without the `Data may be stale`.

!()[https://image.prntscr.com/image/ujjKAyAkR3uug3zZI-RxLg.png]

Once I get a bit more time I'll try digging into the vuex-persist source.  I was just curious if anyone else has ran into this issue or if the config I had above is wrong in some way.

**Comment by championswimmer** [comment]
The filter seems to be applied correct. It does work in the unit tests :open_mouth:

**Comment by cj** [comment]
@championswimmer I see why it's not working as I expected.  https://github.com/championswimmer/vuex-persist/blob/master/src/index.ts#L169-L172 It's saving the entire state regardless of what the mutation is.  So lets say you have a state like:

```javascript
export const state = () => ({
  authenticated: false,
  loggedIn: false,
  data: {},
})
```

and you have 3 mutations `setAuthenticated`, `setLoggedIn` and, `setData`;  If I have the following config that I showed above:

```javascript
const vuexPersist = new VuexPersist({
  asyncStorage: true,
  key: 'vuex',
  storage: localForage,
  filter: mutation => !ignoreMutations.includes(mutation.type),
}).plugin
```

If the mutation `setData` gets called, it is still going to save the state for `authenticated` and `loggedIn`, as it's saving the entire state.  I think what it should do instead is just deep merge in the mutation data.

**Comment by championswimmer** [comment]
You need to use the reducer for that.

Because the library has no way to know "data of *that* mutation"

**Comment by davidgithub1980** [comment]
Same issue here and using _reducer_ having to list almost all modules to be allowed apart from the few ones is quite cumbersome.

**Comment by 672064406zerui** [comment]
Has this problem been solved. If only a few mutatuon are excluded, they are still stored in stroage.
 
Let isSetStroage = mutation.type! = "changeDate"? true:false. 
return isSetStroage

When you change the time, you still store the data.

**Comment by my3188** [comment]
@cj How did you finally solve this problem
