### ISSUE TITLE
Error on creating a new instance

### ISSUE THREAD

**Issue by lucasctd** [championswimmer/vuex-persist#57]
I am getting `"Uncaught TypeError: Cannot read property 'key' of undefined"` when I try to create a new instance of VuexPersistence like this:
`const vuexLocal = new VuexPersistence();`
However, if I do `const vuexLocal = new VuexPersistence({});` It works :v
Any idea?

*PS If it matters, I am not using Typescript.

**Comment by championswimmer** [comment]
Well, for now, pass an empty object. This can be fixed by considering first argument as `{}` if it is undefined

**Comment by lucasctd** [comment]
Okay, thanks.
