### ISSUE TITLE
Opposite of reducer functionality

### ISSUE THREAD

**Issue by elbojoloco** [championswimmer/vuex-persist#58]
Hello, 

The reducer property is useful for defining all the keys you **want** to persist. I am looking for a functionality that does the opposite: where I can define a set of keys that I **don't** want persisted.

Is it currently possible to achieve this? If so, how?

My suggestion would be an `exclude` array with a set of keys, e.g:
`
...
exclude: ['user.password', 'user.email']
...
`

**Comment by championswimmer** [comment]
i will put this onus to the user. no need to bloat the library with this

**Comment by andreasvirkus** [comment]
Please do consider this. For projects with a lot of persisted state properties and maybe a handful of excluded ones, it is a pain to maintain the persistence list.

Also, how would the reduce work for vuex modules?

**Comment by Nolence** [comment]
[redux-persist](https://github.com/rt2zz/redux-persist) has the idea of `whitelisting` and `blacklisting` parts of state which I found really useful while I was working with that library. I don't think it would be out of place to add something like that here.

Anyways, here's what I did to possibly save someone some time:

```javascript
const vuexLocal = new VuexPersistence({
  storage: window.localStorage,
  reducer: state =>
    Object.keys(state).reduce((acc, curr) => {
      if (!["user", /* ... */].includes(curr)) acc[curr] = state[curr];
      return acc;
    }, {})
});
```

**Comment by douglassllc** [comment]
> ```js
> const vuexLocal = new VuexPersistence({
>   storage: window.localStorage,
>   reducer: state =>
>     Object.keys(state).reduce((acc, curr) => {
>       if (!["user", /* ... */].includes(curr)) acc[curr] = state[curr];
>       return acc;
>     }, {})
> });
> ```

Looks interesting as an approach.  I am going to give it a try.  Thanks for posting @Nolence

**Comment by prionkor** [comment]
The solution works. But this could be a built in solution.

**Comment by habaneroofdoom** [comment]
You can use the spread operator to achieve this neatly.
Assume your state has a property "password" you want to exclude, this works quite nicely for me:
```
reducer: (state) => {
    const { password, ...others } = state;
    return others;
  },
```
