### ISSUE TITLE
Persisted state overriding nested properties

### ISSUE THREAD

**Issue by acacia314** [championswimmer/vuex-persist#6]
Say you have a state like:
```
{ a : { b: 0}}
```
that gets persisted to local storage. Then you update your store.js state to
```
{ a : { b: 0, c: 0}}
```
when that app loads the state in local storage will kill _a.c_ because Object.assign is doing a shallow copy on store.state and savedState.
https://github.com/championswimmer/vuex-persist/blob/92035322322021160299780423e7b3987c359f6c/src/index.ts#L122

**Comment by championswimmer** [comment]
Fixed in version 0.2.1 
Please update
