### ISSUE TITLE
Add decorators for marking srore properties persistent

### ISSUE THREAD

**Issue by Koc** [championswimmer/vuex-persist#63]
I am using another your awesome library https://github.com/championswimmer/vuex-module-decorators . And it would be nice provide mode when persistent store properties should be marked with decorators:

```ts
@Module
@ExclusionPolicy("ALL") // exclude all store props by default
export default class MyModule extends VuexModule {
  itemOne = 1
  @Persist // explicit mark this property as persistent
  itemTwo = 2
}
```

**Comment by championswimmer** [comment]
That looks like a delicious idea 😋
But I think it would make sense most as a separate library `vuex-module-persist-decorators` as I would not like to bloat this library with decorators right now, because this works in pure ES5 (without using Babel/Typescript) from a CDN too

**Comment by championswimmer** [comment]
please reopen if still issue remains
