### ISSUE TITLE
lodash.merge adds size to bundle even if lodash is used (deepmerge can be used instead)

### ISSUE THREAD

**Issue by pranavjindal999** [championswimmer/vuex-persist#64]
First, thanks for the awesome plugin.

`vuex-persist` uses `lodash.merge` as one of the dependencies where `lodash.merge` itself is 70% of its code.

![image](https://user-images.githubusercontent.com/5094327/46003422-21f06a00-c0ce-11e8-9e7f-7788a9c101d2.png)
https://bundlephobia.com/result?p=vuex-persist@1.5.4

Even if I use `lodash` in my project, `lodash.merge` adds weight separately because they are independent packages.

Suggestion:
Please consider using [`deepmerge`](https://www.npmjs.com/package/deepmerge) instead of `lodash.merge` which is just 0.5KB gzipped as opposed 3.6 KB gzipped for latter.

**Comment by championswimmer** [comment]
I was using deepmerge earlier and had issues. I'll check again what those were

**Comment by pranavjindal999** [comment]
Didn't knew that we can do that too.. Thanks.
This is what i did (in my webpack config):

```js
resolve: {
      alias: {
        "lodash.merge": path.resolve("./node_modules/lodash/merge.js")
      }
    }
```

It worked and I hope that is what you meant.

**Comment by pranavjindal999** [comment]
Even nooped circular-json as I'm not using that either.

```js
"circular-json": path.resolve("./node_modules/lodash/noop.js")
```

Working fine till now, hope that doesn't create an issue later on.

**Comment by championswimmer** [comment]
done now, it uses deepmerge

**Comment by pranavjindal999** [comment]
Thanks. 👍 
Though you initial solution worked well for me..
