### ISSUE TITLE
(1.6) deepmerge breaks state recovery

### ISSUE THREAD

**Issue by tiagoroldao** [championswimmer/vuex-persist#65]
The move from lodash.merge to deepmerge broke state recovery functionality:

Arrays of elements, instead of being replaced, are merged (concatenated), which adds the defaults to the stored values, instead of replacing them.

**Comment by tiagoroldao** [comment]
Sidenote - currently there are no tests for arrays

**Comment by championswimmer** [comment]
Can you add some array tests?

**Comment by tiagoroldao** [comment]
Once out of work (where we have this dependency) I'll create a PR for fix, with tests.

**Comment by championswimmer** [comment]
fixed in 1.6.1 !
