### ISSUE TITLE
Feature request: reducer-like functionality for data load

### ISSUE THREAD

**Issue by tiagoroldao** [championswimmer/vuex-persist#68]
Currently, we can overwrite the **saveState** and **restoreState** functions, but these imply implementing the storage handling manually.

The **reducer** function maps the state to what we may want to save. A similarly simplified function could enable mapping stored state to vuex state, **without** needing to overwrite the actual storage process.

A use case for this is casting data back into classes, when using them within Vuex.

**Comment by championswimmer** [comment]
please reopen if still issue remains
