### ISSUE TITLE
Version 1.7.2 causing errors in IE11

### ISSUE THREAD

**Issue by andrewgrahamorange** [championswimmer/vuex-persist#73]
We've tried to upgrade vuex-persist to version 1.7.2 from 1.5.3 but we're seeing the following error in Internet Explorer 11 only (not seeing in other browsers):

SCRIPT1002: Syntax error
 "./node_modules/vuex-persist/dist/esm/index.js"

/**
 * Created by championswimmer on 22/07/17.
 */
let MockStorage;
// @ts-ignore
{
    MockStorage = class { **<= Error is thrown here** 
        get length() {
            return Object.keys(this).length;
        }

We're using Vue v2.5.17 and Vuex v3.0.1.

**Comment by championswimmer** [comment]
You need to transpile to ES5 (via your babelrc or webpack config)

**Comment by hiendv** [comment]
Same here. Why don't we target ES5 in the first place?

**Comment by hiendv** [comment]
As the vendor, you should transpile the library https://github.com/championswimmer/vuex-persist/blob/master/build/configs.js#L30

**Comment by championswimmer** [comment]
The size is larger if I make is es5. I want to let the consumer have that option. If he wants to support IE11, he/she can transpile. They're probably having a Vue CLI / Webpack setup already right.

**Comment by hiendv** [comment]
Please continue discussing in the PR #74

**Comment by dombavetta** [comment]
@maxmckenzie You are a life saver.. "frantically trying to deliver a product" was exactly how I would describe my team's efforts last night! Locking to v1.8.0 did the trick.
