### ISSUE TITLE
NPM version is 2.0.0 

### ISSUE THREAD

**Issue by Finrod927** [championswimmer/vuex-persist#77]
There is a vuex-persist 2.0.0 registered in NPM but there are no sign of a 2.0.0 here.

What does it ship?

Also, the fix for #73 seems to not be shipped in 2.0.0. It's not working anymore on IE11

**Comment by jamesalways** [comment]
+1

please fix this problem! Thanks!!!

**Comment by championswimmer** [comment]
done

**Comment by jamesalways** [comment]
Thanks!!!
