### ISSUE TITLE
'Tips for Nuxt' Example Syntax Issue 

### ISSUE THREAD

**Issue by itsMikeLowrey** [championswimmer/vuex-persist#79]
The Syntax is missing a closing bracket ( } ), which causes it to throw an error when nuxt is ran. 
The example is currently:
```
export default ({store}) => {
    window.onNuxtReady(() => {
        new VuexPersistence({
            /* your options */
        }).plugin(store);
    );
}
```
It should read: 
```
export default ({ store }) => {
  window.onNuxtReady(() => {
    new VuexPersistence({
    /* your options */
    }).plugin(store);
  });
}
```

This worked for my deployment. Great library by the way.

**Comment by championswimmer** [comment]
Make a PR to fix it if you want to :-)

I'll do it otherwise, ofcourse, but would love have your contribution on
the repository since you found the error
