### ISSUE TITLE
How to Use Cookie Storage in Nuxt

### ISSUE THREAD

**Issue by Caoyiii** [championswimmer/vuex-persist#81]
my code is as follow:
in vuex-persist.js

    import VuexPersistence from 'vuex-persist'
    import Cookies from 'js-cookie'

    export default ({ store }) => {
      window.onNuxtReady(() => {
        new VuexPersistence({
          key: 'wishlist',
          restoreState: (key, storage) => Cookies.getJSON(key),
          saveState: (key, state, storage) =>
            Cookies.set(key, state, {
              expires: 3
           }),
          reducer: state => {
           return { wishlist: state.wishList }
          }
        }).plugin(store)
      })
    }

but state will disappear after the refresh, cookie has not been saved.

**Comment by championswimmer** [comment]
Did you figure out?

**Comment by Caoyiii** [comment]
in vuex-persist.js

    import VuexPersistence from 'vuex-persist'
    import Cookies from 'js-cookie'

    export default ({ store, req, app }) => {
      new VuexPersistence({
        restoreState: (key, storage) => Cookies.getJSON(key),
        saveState: (key, state, storage) =>
          Cookies.set(key, state, {
            expires: 30
         }),
        modules: ['cart', 'users', 'wishlist']
      }).plugin(store)
    }

it can run，but I want to get State in NUXT AsyncData() SSR  and must pass nuxtServerInit Can it be realized.
or

    restoreState: (key, storage) =>
         process.server ? cookie.parse(req.headers.cookie) : Cookies.getJSON(key)
but vuex-persist is client plugin, It can't run.

Do you have a better solution?
