### ISSUE TITLE
Migrating existing data from localStorage

### ISSUE THREAD

**Issue by jetlej** [championswimmer/vuex-persist#84]
I was previously using localStorage without vuex or vuex-persist for data. Is there a way for me to migrate that data into the new vuex-persist storage?

**Comment by jetlej** [comment]
I'm doing this, but state.tasks is still showing up empty. However running `window.localStorage.getItem('tasks')` in the browser console returns the right value.

```
const vuexLocalStorage = new VuexPersist({
  restoreState: (key, storage) => window.localStorage.getItem('tasks'),
  saveState: (key, state, storage) => window.localStorage.setItem('tasks', state)
})

const store = new Vuex.Store({
  state: {
    tasks: []
  },
  plugins: [vuexLocalStorage.plugin],
  strict: process.env.NODE_ENV !== 'production'
})
```

**Comment by championswimmer** [comment]
`restoreState` should return the exact shape of the state

```
restoreState: (key, storage) => ({tasks: JSON.parse(window.localStorage.getItem('tasks'))}),
```

**Comment by jetlej** [comment]
That worked, thank you!
