### ISSUE TITLE
Default support for Vuex strict mode

### ISSUE THREAD

**Issue by danlake** [championswimmer/vuex-persist#9]
I using Vuex in strict mode, an error is thrown as persist attempts to mutate states outside of mutation handlers.

It would be nice if persist could support strict mode in dev. I can turn strict mode off for now, but when the codebase is shared between multiple devs in a team, strict mode ensures good practices.

I don't know whether this is a feature request or if I've missed something?

**Comment by championswimmer** [comment]
Afaik, strict mode is not for deployment.

**Comment by championswimmer** [comment]
Well, we have support in v0.3.0 now :) 
https://github.com/championswimmer/vuex-persist/commit/7478334afff81d44a0422682657bb2b9824c8ccd
