### ISSUE TITLE
Using vuex-persist with Nuxt. How do I access the store in a component.

### ISSUE THREAD

**Issue by kpturner** [championswimmer/vuex-persist#91]
I am using `nuxt.js` with Typescript.
I have setup `vuex-persist` for `nuxt.js` as defined in the readme like this:

**vuex-persist.ts**
```
import VuexPersistence from 'vuex-persist';
import { IState } from '../types/store';

export default ({ store }) => {
    window['onNuxtReady'](() => {
        new VuexPersistence({
            reducer: (state: IState) => ({ formJ: state.formJ })
        }).plugin(store);
    });
};
```
And registering in `nuxt.config.ts` like this:
```
plugins: [
        { src: '~/plugins/vuex-persist', ssr: false }
    ],
```

and I find that more `formJ` store is getting persisted as expected in `window.localStorage` (`formJ` is a module by the way).

What I am completely clueless about is how I can ensure this is accessed by a component on the client-side when the user does a page refresh.  At the moment everything works via normal `vuex` fine until you do a page refresh and the state is lost. 

I am setting the state on the page with an `action` on the vuex store in `asyncdata` and retrieving it with `getter` in `computed` in a component.  

I was naively expecting the `getter` to go to the localStorage copy of the state when the user does a page refresh but that is not the case. So my question is, how does one force a component (or page) to get the state using a getter via the store created with `vuex-persist`?

I can't use `this.$store) it seems to presumably I have to import the vuex-persist store and use that?

**Comment by kpturner** [comment]
I think I have discovered that my error is being generated on the server before hydration so I need to have a rethink.

**Comment by Jozaguts** [comment]
Did you solve it?
