### ISSUE TITLE
[BUG] The compiled distribution script contains es5 keyword "let"

### ISSUE THREAD

**Issue by Haixing-Hu** [championswimmer/vuex-persist#94]
Therefore the script failed to execute on some old browser, such as Safari 9.1

**Comment by championswimmer** [comment]
please refer https://github.com/championswimmer/vuex-persist#transpile-for-target-es5

**Comment by avennn** [comment]
> please refer https://github.com/championswimmer/vuex-persist#transpile-for-target-es5

It is not working.
