### ISSUE TITLE
localForage object storage failure case

### ISSUE THREAD

**Issue by kpdemetriou** [championswimmer/vuex-persist#97]
When using `localForage` storage and the `localForage` configuration `name` is customized, object storage no longer works and vuex-persist falls back to serialization. Fixing this bug requires changing the method used to identify `localForage` in `index.ts`.

**Comment by morphatic** [comment]
Good catch. [Here's the line of code where this is implemented](https://github.com/championswimmer/vuex-persist/blob/master/src/index.ts#L145).
